services:
  # Сервис для базы данных PostgreSQL
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    expose:
      - "5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Сервис для нашего Django-приложения
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    user: "${UID}:${GID}"
    volumes:
      # Синхронизирует текущую папку с папкой /app внутри контейнера
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=db
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
    # Указывает, что сервис web должен стартовать после сервиса db
    depends_on:
      db:
        condition: service_healthy

volumes:
  # Docker будет управлять этим томом, чтобы данные БД не терялись при перезапуске
  postgres_data: