# Generated by Django 5.2.4 on 2025-07-09 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название игровой системы, например, Daggerheart', max_length=100, unique=True)),
                ('version', models.CharField(blank=True, help_text='Версия системы, например, 1.0', max_length=20)),
                ('slug', models.SlugField(help_text="Короткое имя для URL, например, 'daggerheart'", unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Доп. поля, например, вес, стоимость и т.д.')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.gamesystem')),
            ],
            options={
                'unique_together': {('name', 'system')},
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название особенности', max_length=200)),
                ('description', models.TextField(help_text='Подробное описание того, что делает особенность')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='core.gamesystem')),
            ],
            options={
                'unique_together': {('name', 'system')},
            },
        ),
        migrations.CreateModel(
            name='DamageType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название типа урона', max_length=50)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='damage_types', to='core.gamesystem')),
            ],
            options={
                'unique_together': {('name', 'system')},
            },
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('features', models.ManyToManyField(blank=True, related_name='communities', to='core.feature')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communities', to='core.gamesystem')),
            ],
            options={
                'verbose_name_plural': 'Communities',
                'unique_together': {('name', 'system')},
            },
        ),
        migrations.CreateModel(
            name='CharacterClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('features', models.ManyToManyField(blank=True, related_name='classes', to='core.feature')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='core.gamesystem')),
            ],
            options={
                'verbose_name_plural': 'Character Classes',
                'unique_together': {('name', 'system')},
            },
        ),
        migrations.CreateModel(
            name='Ancestry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('features', models.ManyToManyField(blank=True, related_name='ancestries', to='core.feature')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ancestries', to='core.gamesystem')),
            ],
            options={
                'verbose_name_plural': 'Ancestries',
                'unique_together': {('name', 'system')},
            },
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.item')),
                ('damage_dice', models.CharField(help_text="Кости урона, например, '1d8' или '2d6'", max_length=50)),
                ('damage_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='weapons', to='core.damagetype')),
            ],
            bases=('core.item',),
        ),
    ]
