# Generated by Django 5.2.4 on 2025-07-09 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Имя персонажа', max_length=200)),
                ('level', models.PositiveIntegerField(default=1)),
                ('current_hp', models.IntegerField(default=10, help_text='Текущие хиты')),
                ('max_hp', models.IntegerField(default=10, help_text='Максимальные хиты')),
                ('strength', models.IntegerField(default=0)),
                ('finesse', models.IntegerField(default=0)),
                ('agility', models.IntegerField(default=0)),
                ('instinct', models.IntegerField(default=0)),
                ('presence', models.IntegerField(default=0)),
                ('knowledge', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ancestry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characters', to='core.ancestry')),
                ('character_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characters', to='core.characterclass')),
                ('community', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characters', to='core.community')),
                ('player', models.ForeignKey(help_text='Пользователь, владеющий персонажем', on_delete=django.db.models.deletion.CASCADE, related_name='characters', to=settings.AUTH_USER_MODEL)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='character_sheets', to='core.gamesystem')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('is_equipped', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_inventories', to='core.item')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='characters.charactersheet')),
            ],
            options={
                'verbose_name_plural': 'Character Inventories',
                'unique_together': {('character', 'item')},
            },
        ),
    ]
