name: TTRPG Backend CI

# Триггеры: запускать при пуше в main или при создании/обновлении Pull Request на main
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flake8 pytest # Устанавливаем инструменты для тестов и линтинга

    - name: Check formatting with Black
      run: |
        # Флаг --check говорит Black не изменять файлы, а только
        # проверить, нужно ли их изменять. Если нужно - он выйдет с ошибкой.
        black --check .

    - name: Lint with flake8
      run: |
        flake8 . --count --show-source --statistics

    - name: Run Tests
      run: |
        echo "No tests to run yet."
        # Заглушка, чтобы шаг считался успешным
        exit 0